import {t} from 'elysia'
import {YapockType} from '@/index'
import requiresUserProfile from '@/utils/identity/requires-user-profile'
import prisma from '@/db/prisma'

export default (app: YapockType) => app
    .get('', async ({set, user}) => {
        await requiresUserProfile({set, user})

        // 'id' as 'invite_code'
        let invites = await prisma.invites.findMany({
            where: {invited_by: user.sub},
            select: {id: true, invite_id: true, created_at: true}
        })
        if (!invites) invites = []

        return invites.map((invite: any) => {
            return {
                invite_id: invite.invite_id,
                created_at: invite.created_at.toISOString(),
            }
        })

    }, {
        detail: {
            description: 'Get all invites generated by current user.',
            tags: ['Invite']
        },
        response: {
            200: t.Array(t.Object({
                invite_id: t.String(),
                created_at: t.String()
            })),
            404: t.Void()
        }
    })
