import {t} from 'elysia'
import {YapockType} from '@/index'
import requiresUserProfile from '@/utils/identity/requires-user-profile'
import supabase from '@/utils/supabase/client'
import prisma from '@/db/prisma'

export default (app: YapockType) => app
    .get('', async ({set, user}) => {
        await requiresUserProfile({set, user})

        // 'id' as 'invite_code'
        let invites = await prisma.waitlist.findMany({
            where: { owner_id: user.sub },
            select: { id: true, owner_id: true, created_at: true }
        });
        if (!invites) invites = []

        return invites.map((invite: any) => {
            return {
                invite_code: invite.id,
                owner_id: invite.owner_id,
                created_at: invite.created_at.toISOString(),
            }
        })

    }, {
        detail: {
            description: 'Get all invites generated by current user.',
            tags: ['Invite']
        },
        response: {
            200: t.Array(t.Object({
                invite_code: t.String(),
                owner_id: t.String(),
                created_at: t.String(),
            })),
            404: t.Void()
        }
    })
